"""Add reminder_sent to Reminder

Revision ID: 01214b71508c
Revises: b03a60291a8a
Create Date: 2025-11-04 10:46:56.764798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01214b71508c'
down_revision = 'b03a60291a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_column('reminder_sent')

    # ### end Alembic commands ###
