"""Tambah kolom dp di service_type

Revision ID: 027577959b47
Revises: 6592cbbf6702
Create Date: 2025-11-07 20:10:08.928070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027577959b47'
down_revision = '6592cbbf6702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('dp')

    with op.batch_alter_table('service_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dp', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_type', schema=None) as batch_op:
        batch_op.drop_column('dp')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dp', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
