"""add template

Revision ID: 25af3b59b8b1
Revises: 969ce8e1f362
Create Date: 2026-02-25 09:32:05.785641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25af3b59b8b1'
down_revision = '969ce8e1f362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('nomor_wa',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template', sa.String(length=20), nullable=True))

    with op.batch_alter_table('service_motor_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'service_motor', ['service_motor_id'], ['id'])

    # ### end Alembic commands ###


from alembic import op
import sqlalchemy as sa


def upgrade():
    op.add_column('invoice',
        sa.Column('template', sa.String(length=20), nullable=True)
    )


def downgrade():
    op.drop_column('invoice', 'template')

    # ### end Alembic commands ###
