"""Tambah field lengkap di Technician

Revision ID: 35b8dca1b6fa
Revises: 5ef7011738f4
Create Date: 2025-10-06 21:31:03.466919
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b8dca1b6fa'
down_revision = '5ef7011738f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - telah diperbaiki untuk SQLite ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.alter_column('unit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tanggal',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        # ❌ Hapus drop_constraint tanpa nama karena SQLite tidak mendukung
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(batch_op.f('fk_claim_service'), type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')

        # ✅ Pastikan relasi tetap ada
        # Jika constraint lama sudah ada, create_foreign_key akan diabaikan
        batch_op.create_foreign_key('fk_claim_service', 'service', ['service_id'], ['id'])
        batch_op.create_foreign_key('fk_claim_customer', 'customer', ['customer_id'], ['id'])
        batch_op.create_foreign_key('fk_claim_unit', 'ac_unit', ['unit_id'], ['id'])

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_invoice_customer', 'customer', ['customer_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_invoiceitem_invoice', 'invoice', ['invoice_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.alter_column('keterangan_reminder',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Belum di-Reminder'"))

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('jenis_service',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('technician', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jabatan', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('no_hp', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('alamat', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tanggal_masuk', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gaji_pokok', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('catatan', sa.Text(), nullable=True))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_transaction_service', 'service', ['service_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - telah diperbaiki ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_service', type_='foreignkey')

    with op.batch_alter_table('technician', schema=None) as batch_op:
        batch_op.drop_column('catatan')
        batch_op.drop_column('gaji_pokok')
        batch_op.drop_column('status')
        batch_op.drop_column('tanggal_masuk')
        batch_op.drop_column('alamat')
        batch_op.drop_column('no_hp')
        batch_op.drop_column('jabatan')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('jenis_service',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.alter_column('keterangan_reminder',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Belum di-Reminder'"))

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invoiceitem_invoice', type_='foreignkey')
        batch_op.create_foreign_key('fk_invoiceitem_invoice_old', 'invoice', ['invoice_id'], ['id'])

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invoice_customer', type_='foreignkey')
        batch_op.create_foreign_key('fk_invoice_customer_old', 'customer', ['customer_id'], ['id'])

    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.drop_constraint('fk_claim_service', type_='foreignkey')
        batch_op.drop_constraint('fk_claim_customer', type_='foreignkey')
        batch_op.drop_constraint('fk_claim_unit', type_='foreignkey')
        batch_op.create_foreign_key('fk_claim_unit_old', 'ac_unit', ['unit_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_claim_service_old', 'service', ['service_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_claim_customer_old', 'customer', ['customer_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('tanggal',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('unit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
