"""Add ruangan to ACUnit

Revision ID: 465a2e15558b
Revises: 846ee7acb32b
Create Date: 2025-10-31 14:44:14.786121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465a2e15558b'
down_revision = '846ee7acb32b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ac_unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruangan', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ac_unit', schema=None) as batch_op:
        batch_op.drop_column('ruangan')

    # ### end Alembic commands ###
