"""add total_tidak_hadir to payroll

Revision ID: 4778da81fc1f
Revises: 9f53084b1fd0
Create Date: 2025-10-07 23:26:13.943181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4778da81fc1f'
down_revision = '9f53084b1fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_tidak_hadir', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_column('total_tidak_hadir')

    # ### end Alembic commands ###
