"""Add PayrollLog model

Revision ID: 4ed747c4f62c
Revises: 05d9da9c12d9
Create Date: 2025-10-27 22:10:09.371730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed747c4f62c'
down_revision = '05d9da9c12d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kasbon', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_kasbon_payroll_id'), type_='foreignkey')
        batch_op.drop_column('payroll_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kasbon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payroll_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_kasbon_payroll_id'), 'payroll', ['payroll_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
