"""add attendance table

Revision ID: 5b1a07642638
Revises: b8e0dbfae850
Create Date: 2025-10-07 11:47:07.192658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1a07642638'
down_revision = 'b8e0dbfae850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('jam_masuk', sa.Time(), nullable=True),
    sa.Column('jam_pulang', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('lokasi', sa.String(length=100), nullable=True),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['technician_id'], ['technician.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('salary_history')
    with op.batch_alter_table('technician', schema=None) as batch_op:
        batch_op.alter_column('foto',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('dokumen',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technician', schema=None) as batch_op:
        batch_op.alter_column('dokumen',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('foto',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    op.create_table('salary_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('periode', sa.VARCHAR(length=20), nullable=False),
    sa.Column('gaji_pokok', sa.FLOAT(), nullable=True),
    sa.Column('bonus', sa.FLOAT(), nullable=True),
    sa.Column('potongan', sa.FLOAT(), nullable=True),
    sa.Column('total_gaji', sa.FLOAT(), nullable=True),
    sa.Column('dibayarkan_tanggal', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['technician.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('attendance')
    # ### end Alembic commands ###
