"""Add DP field to Service

Revision ID: 6592cbbf6702
Revises: dc2754a556fc
Create Date: 2025-11-07 15:19:15.753972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6592cbbf6702'
down_revision = 'dc2754a556fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dp', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('dp')

    # ### end Alembic commands ###
