"""Add terpilih column to Kasbon

Revision ID: 6c6d40aae671
Revises: 3a8067f140ff
Create Date: 2025-10-26 11:07:16.871998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6d40aae671'
down_revision = '3a8067f140ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kasbon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terpilih', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kasbon', schema=None) as batch_op:
        batch_op.drop_column('terpilih')

    # ### end Alembic commands ###
