"""Tambah kolom terpilih di service_motor

Revision ID: 846ee7acb32b
Revises: de9100de56ba
Create Date: 2025-10-29 23:03:17.250748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846ee7acb32b'
down_revision = 'de9100de56ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_motor_ids', sa.PickleType(), nullable=True))

    with op.batch_alter_table('service_motor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terpilih', sa.Boolean(), nullable=True))
        batch_op.alter_column('tanggal',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('porsi_teknisi',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('porsi_perusahaan',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('keterangan',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_motor', schema=None) as batch_op:
        batch_op.alter_column('keterangan',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('porsi_perusahaan',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('porsi_teknisi',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('tanggal',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('terpilih')

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_column('service_motor_ids')

    # ### end Alembic commands ###
