"""add payroll totals

Revision ID: 84d258acc22d
Revises: ba1ab74059da
Create Date: 2025-10-09 22:25:15.650577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d258acc22d'
down_revision = 'ba1ab74059da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_pendapatan', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_potongan', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gaji_bersih', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tanggal_dibuat', sa.DateTime(), nullable=True))
        batch_op.alter_column('periode',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=7),
               existing_nullable=False)
        batch_op.drop_column('uang_makan')
        batch_op.drop_column('uang_bensin')
        batch_op.drop_column('bonus_bulanan')
        batch_op.drop_column('potongan_service')
        batch_op.drop_column('potongan_absen')
        batch_op.drop_column('potongan_kasbon')
        batch_op.drop_column('gaji_pokok')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gaji_pokok', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('potongan_kasbon', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('potongan_absen', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('potongan_service', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('bonus_bulanan', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('uang_bensin', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('uang_makan', sa.FLOAT(), nullable=True))
        batch_op.alter_column('periode',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('tanggal_dibuat')
        batch_op.drop_column('gaji_bersih')
        batch_op.drop_column('total_potongan')
        batch_op.drop_column('total_pendapatan')

    # ### end Alembic commands ###
