"""add total_tidak_hadir to payroll

Revision ID: 9f53084b1fd0
Revises: 5686ff885a45
Create Date: 2025-10-07 23:20:38.768917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f53084b1fd0'
down_revision = '5686ff885a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll_item')
    op.drop_table('salary_history')
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.alter_column('periode',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_column('gaji_bersih')
        batch_op.drop_column('total_potongan')
        batch_op.drop_column('total_pendapatan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_pendapatan', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('total_potongan', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('gaji_bersih', sa.FLOAT(), nullable=True))
        batch_op.alter_column('periode',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    op.create_table('salary_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('periode', sa.VARCHAR(length=20), nullable=True),
    sa.Column('gaji_pokok', sa.FLOAT(), nullable=True),
    sa.Column('bonus', sa.FLOAT(), nullable=True),
    sa.Column('potongan', sa.FLOAT(), nullable=True),
    sa.Column('total_gaji', sa.FLOAT(), nullable=True),
    sa.Column('dibayarkan_tanggal', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['technician.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('payroll_id', sa.INTEGER(), nullable=False),
    sa.Column('kategori', sa.VARCHAR(length=20), nullable=True),
    sa.Column('deskripsi', sa.VARCHAR(length=100), nullable=True),
    sa.Column('jumlah', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['payroll_id'], ['payroll.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
