"""add persen to service motor

Revision ID: 9fe1139897f1
Revises: 6aee9b5d7739
Create Date: 2026-01-17 12:05:28.395666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe1139897f1'
down_revision = '6aee9b5d7739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_motor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persen_teknisi', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('persen_perusahaan', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_motor', schema=None) as batch_op:
        batch_op.drop_column('persen_perusahaan')
        batch_op.drop_column('persen_teknisi')

    # ### end Alembic commands ###
