"""add pendapatan_tipe to transaction

Revision ID: a1f4c3e796e3
Revises: a0bc7f1fa2c3
Create Date: 2025-09-07 21:05:54.936266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f4c3e796e3'
down_revision = 'a0bc7f1fa2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('nomor_wa',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        # kasih nama unik biar valid
        batch_op.create_unique_constraint('uq_customer_nomor_wa', ['nomor_wa'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pendapatan_tipe', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('technician_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('technician_nama', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('team', sa.String(length=50), nullable=True))
        # kasih nama foreign key biar valid
        batch_op.create_foreign_key('fk_transaction_technician_id', 'technician', ['technician_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_technician_id', type_='foreignkey')
        batch_op.drop_column('team')
        batch_op.drop_column('technician_nama')
        batch_op.drop_column('technician_id')
        batch_op.drop_column('pendapatan_tipe')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint('uq_customer_nomor_wa', type_='unique')
        batch_op.alter_column('nomor_wa',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
