"""Add kasbon_ids to Payroll

Revision ID: a54d068797e6
Revises: 4ed747c4f62c
Create Date: 2025-10-27 22:22:32.078680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54d068797e6'
down_revision = '4ed747c4f62c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kasbon_ids', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_column('kasbon_ids')

    # ### end Alembic commands ###
