"""Fix ACUnit-Service relationship

Revision ID: b03a60291a8a
Revises: 7e07cc190359
Create Date: 2025-10-31 23:18:55.425513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03a60291a8a'
down_revision = '7e07cc190359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_service_ac_unit'), type_='foreignkey')
        batch_op.drop_column('ac_unit_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ac_unit_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_service_ac_unit'), 'ac_unit', ['ac_unit_id'], ['id'])

    # ### end Alembic commands ###
