"""Tambah kolom foto dan dokumen ke technician

Revision ID: b8e0dbfae850
Revises: 35b8dca1b6fa
Create Date: 2025-10-07 10:20:11.023186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e0dbfae850'
down_revision = '35b8dca1b6fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technician', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('dokumen', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technician', schema=None) as batch_op:
        batch_op.drop_column('dokumen')
        batch_op.drop_column('foto')

    # ### end Alembic commands ###
