"""add payroll setting and item tables

Revision ID: ba1ab74059da
Revises: 4778da81fc1f
Create Date: 2025-10-09 15:39:37.446397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1ab74059da'
down_revision = '4778da81fc1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gaji_pokok_default', sa.Float(), nullable=True),
    sa.Column('uang_makan_harian', sa.Float(), nullable=True),
    sa.Column('uang_bensin_harian', sa.Float(), nullable=True),
    sa.Column('bonus_bulanan_default', sa.Float(), nullable=True),
    sa.Column('potongan_absen_per_hari', sa.Float(), nullable=True),
    sa.Column('potongan_kasbon_default', sa.Float(), nullable=True),
    sa.Column('potongan_service_default', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_id', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=20), nullable=True),
    sa.Column('deskripsi', sa.String(length=100), nullable=True),
    sa.Column('jumlah', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['payroll_id'], ['payroll.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll_item')
    op.drop_table('payroll_setting')
    # ### end Alembic commands ###
