"""Add bank_account table

Revision ID: caa8be899049
Revises: 027577959b47
Create Date: 2025-12-10 11:03:46.687818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa8be899049'
down_revision = '027577959b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_type', schema=None) as batch_op:
        batch_op.drop_column('dp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dp', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
