"""Add spreadsheet_link to Invoice

Revision ID: dc2754a556fc
Revises: 01214b71508c
Create Date: 2025-11-06 14:34:26.022252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2754a556fc'
down_revision = '01214b71508c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spreadsheet_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('spreadsheet_link')

    # ### end Alembic commands ###
