"""Add payroll_id to Kasbon

Revision ID: de9100de56ba
Revises: a54d068797e6
Create Date: 2025-10-27 22:34:49.232052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de9100de56ba'
down_revision = 'a54d068797e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kasbon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payroll_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_kasbon_payroll', 'payroll', ['payroll_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kasbon', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('payroll_id')

    # ### end Alembic commands ###
